microsoft/MLOpsPython

docs/getting_started.md, environment_setup/arm-templates/cloud-environment.json, environment_setup/iac-create-environment.yml, environment_setup/iac-remove-environment.yml, ml_service/pipelines/build_train_pipeline.py, ml_service/util/create_scoring_image.py, ml_service/util/register_model.py, tests/unit/code_test.py
=> Unique Base Name 

.env.example, .pipelines/azdo-ci-build-train.yml, code/evaluate/evaluate_model.py, code/training/train.py, docs/code_description.md, docs/getting_started.md, environment_setup/arm-templates/cloud-environment.json, environment_setup/docker-image-pipeline.yml, environment_setup/iac-create-environment.yml, environment_setup/requirements.txt, ml_service/pipelines/build_train_pipeline.py, ml_service/pipelines/run_train_pipeline.py, ml_service/util/attach_compute.py
I've refactored the training pipeline to use the SDK in each step (train and evaluate) to track each run via the Release ID, and then dynamically look up the run metrics, rather than storing them in intermediary JSON files.
This update also tags the Azure ML pipeline with a "version" matching the Build ID, and then each child run has the property of "release-id" matching the AzDO Release ID that triggered the pipeline run. This should help improve traceability from model, to run, and back to build.
A few notes: 
- This update also removes the separate  "register_model_step" in the pipeline and registers the model (based on performance) in the evaluate_step. I have left the code for the register step in as a legacy snippet.
- PipelineData and Pipeline Inputs/outputs are no longer required …
=> Updated repo to use the SDK more consistently 

code/evaluate/evaluate_model.py, code/register/register_model.py, code/util/model_helper.py, ml_service/pipelines/run_train_pipeline.py, ml_service/util/env_variables.py
Fixes the use case where there are multiple experiments registering models in a workspace - we should only evaluate the models from the experiment not ALL models in the workspace.
=> Generalize model tag finder, tag model experiment_name

.pipelines/azdo-ci-build-train.yml, code/evaluate/evaluate_model.py, code/register/register_model.py, ml_service/pipelines/run_train_pipeline.py
=> Add code comments

docs/getting_started.md
Added some clarifications and fixed some typos in the getting started guide.
=> Making clarifications in Getting Started guide

code/evaluate/evaluate_model.py, code/register/register_model.py, code/training/train.py, ml_service/pipelines/build_train_pipeline.py, ml_service/util/env_variables.py
=> Tag the experiment runs and model with a link to the build ui

code/register/register_model.py
If the builduri_base is None, the build_uri would never been instantiated causing an error when calling register_aml_model(model_name, exp, run_id, build_id, build_uri). By adding the else statement, this is prevented.
=> Fixed assignment bug for build_uri

.pipelines/azdo-ci-build-train.yml, code/evaluate/evaluate_model.py, ml_service/pipelines/verify_train_pipeline.py, ml_service/util/create_scoring_image.py
There is a parameter for the location of the "code" folder (SOURCES_DIR_TRAIN), but it isn't used everywhere. This change updates it to be used in all the python and yml scripts.
=> extending use of SOURCES_DIR_TRAIN variable

.pipelines/diabetes_regression-ci-build-train.yml
Set the ci-build-train pipeline to always run the evaluation step (even if the pipeline is cancelled). This will cause the Azure Pipeline to log the reason for cancellation rather than just "silently failing".
#151
=> Always run the pipeline evaluation step

.pipelines/azdo-base-pipeline.yml, README.md, data/data_test.py, diabetes_regression/ci_dependencies.yml, diabetes_regression/training/test_train.py, docs/development_setup.md, docs/getting_started.md, lint-and-test.sh, tox.ini
- Fixed test_train_model test in code_test.py
- Renamed code_test.py to train_test.py
- Moved train_test.py under diabetes_regression directory
- Moved data_test.py under data directory
- Added lint and unit test tasks to azdo-base-pipeline.yml
- Deleted lint-and-test.sh and tox.ini
=> Fixed and rearranged unit tests

bootstrap/README.md, bootstrap/bootstrap.py, diabetes_regression/register/register_model.py, ml_service/util/create_scoring_image.py
Rename all remaining traces of the word "diabetes" in the code base.
=> bootstrap diabetes cleanup

.env.example, diabetes_regression/evaluate/evaluate_model.py, diabetes_regression/register/register_model.py, diabetes_regression/training/train.py, docs/getting_started.md, ml_service/pipelines/diabetes_regression_build_train_pipeline.py, ml_service/util/env_variables.py
I modified the pipeline to be more "AMLish":
- Added instructions to Getting Started to register a dataset (or set variables for the pipeline to do it for you)
- Used input in training step to pass dataset object
- Added pipelinedata object to pass trained model as output from train step and input to register step
=> Modified to use dataset and pipelinedata

.pipelines/azdo-base-pipeline.yml
Just a condition to run unit tests even in the case if linting is not completed successfully. Potentially, it can reduce number of pipeline calls because devs will be able to see all problems at the same time rather than find them one by one
=> run unit tests in any case

.pipelines/azdo-abtest-pipeline.yml, .pipelines/azdo-base-pipeline.yml, .pipelines/azdo-helm-install.yml, .pipelines/azdo-helm-upgrade.yml, .pipelines/azdo-pr-build-train.yml, .pipelines/diabetes_regression-ci-build-train.yml, .pipelines/diabetes_regression-ci-image.yml, .pipelines/diabetes_regression-template-get-model-version.yml, .pipelines/diabetes_regression-variables.yml, environment_setup/docker-image-pipeline.yml, environment_setup/iac-create-environment.yml, environment_setup/iac-remove-environment.yml
Added some basic descriptions and did some drive-by whitespace cleanup.
=> Add basic descriptions to YAML pipelines

docs/getting_started.md
It might be obvious when you know what the task does, but it wasn't obvious to me to I've clarified the wording.
=> Clarify that web app must exist for the web app deploy to work

.pipelines/diabetes_regression-ci-build-train.yml
It is not clear from the docs, but looking at the source code for the AzureWebAppContainer task it need a resource group and an image name (as opposed to container name). These parameters deploy successfully for me.
I'm not sure about the azureSubscription value, it might not be needed but I've left it as it was.
=> Use correct parameter names in web app deploy

.pipelines/diabetes_regression-ci-build-train.yml, .pipelines/diabetes_regression-template-get-model-version.yml, .pipelines/diabetes_regression-variables.yml, README.md, docs/getting_started.md
Allows you to skip the first two stages of the pipeline and deploy a model registered by a previous build by setting the variable `MODEL_BUILD_ID` to the previous build's id when queuing the pipeline. This speeds up the process of fixing issues with the scoring or deployment configuration.
Also some auto lint fixes.
=> Enable deploy of model registered by previous build

.pipelines/diabetes_regression-ci-build-train.yml
Fixing regression introduced in #207 - don't continue pipeline on lint/unit test errors.
=> ci-build-train pipeline condition fix

docs/getting_started.md
Some fixes based on Eugene's feedback.
- Ordered the descriptions to match the table
- Added ACI description
- Added location description and link
- Fixed ACI acronym description
Additional changes
- Added a clarification that the variables with Azure resource names don't have to exist yet
- Removed 'diabetes' from the name of ACI and AKS deployments and switched to generic 'mlops' to match the other resource naming convention
=> Getting Started fixes for the Variable Group section

.pipelines/abtest.yml, charts/abtest-model/templates/deployment.yaml
- Use the variable template so we don't have to manually define MODEL_NAME and MODEL_VERSION
- Upgrade helm version to 3.1.1 to fix some issues
- Enable ACR authentication using service principals rather than a manual secret
=> Canary pipeline fixes

docs/canary_ab_deployment.md
- Spelling & grammar
- Formatting and linting fixes
- Prerequisite section showing assumptions
- Table of contents
- Suggested values to match Getting Started guide
=> Improve Canary guide and add prerequisites

diabetes_regression/evaluate/evaluate_model.py, diabetes_regression/util/model_helper.py, ml_service/pipelines/diabetes_regression_verify_train_pipeline.py
The get_latest_model method helps to get the latest model without providing a specific tag.
=> Added get_latest_model method

diabetes_regression/evaluate/evaluate_model.py, diabetes_regression/parameters.json, diabetes_regression/register/register_model.py, diabetes_regression/training/train_aml.py
Added a registration section to parameters.json. If the keys found in the "tags" section are found as tags on the parent run, the tag will be applied to the model. 
The registration doesn't fail if the tag is not found.
=> Model registration tags come from parameters.json

docs/getting_started.md
=> update doc with aks auth details

docs/custom_container.md, environment_setup/docker-image-pipeline.yml
=> Sudivate dockertag

ml_service/pipelines/diabetes_regression_build_train_pipeline.py
#140 
Set the training step to reuse the results from previous runs. If there are no new changes made in the training script this will avoid re-running the training scripts and reduce the time for train step from ~2.95 mins to `42 secs
=> Sudivate allow reuse

README.md, bootstrap/README.md, docs/code_description.md, docs/custom_model.md, docs/getting_started.md
Migrating the bring-your-own-code guide from the end of https://docs.microsoft.com/en-us/azure/machine-learning/tutorial-convert-ml-experiment-to-production to the MLOpsPython repo.
Also moves some of the content from the bootstrap readme into the new guide instead.
=> Moving code integration guide into this repo

docs/getting_started.md
At the moment we're explaining the pipeline stages in paragraph form, this change breaks it out into bullet points and reduces unnecessary verbosity
=> Clearer explanation of the pipeline stages in the getting started guide

bootstrap/README.md, bootstrap/bootstrap.py, ml_service/pipelines/diabetes_regression_build_train_pipeline.py, ml_service/pipelines/load_sample_data.py
- Project name is now additionally restricted to letters and underscores
- Fix an issue where we try to load a non-existant dataset from sklearn after bootstrapping
- Added some general error handling
- Standardized arguments to short and long forms & updated README
- General code cleanup
=> Bootstrap fixes

ml_service/util/create_scoring_image.py
Update Image creation to use the new package
=> Update Image creation to use new package

diabetes_regression/conda_dependencies.yml
Azure deprecated their top level meta-package which led to a deprecation error. We don't actually need this top level package.
I took the opportunity to clean up the conda deps using the dependency tree.
- Trimmed the package list
- Explicitly list pip to avoid conda warning
- Use azureml-defaults for WebApp dependencies
- Lock azureml-sdk and azureml-defaults versions
- Add comments for dependencies
=> Fix training/scoring conda deps

diabetes_regression/ci_dependencies.yml
- Tied SDK version to 1.2.x as with conda_dependencies.yml
- Allow deps to fall out based on SDK
- Kept the rest of the deps manually specified to keep image size small and minimize regressions
Passing build at https://aidemos.visualstudio.com/MLOps/_build/results?buildId=4388&view=results
Test image deployed at mcr.microsoft.com/mlops/python:tcare-test
=> Update CI conda deps to match training/scoring SDK

environment_setup/docker-image-pipeline.yml
The docker pipeline fails to tag because the trailing whitespace gets included in the tag name.
Successful run at https://aidemos.visualstudio.com/MLOps/_build/results?buildId=4398&view=results
=> Fix docker pipeline by removing trailing whitespace

diabetes_regression/ci_dependencies.yml, diabetes_regression/conda_dependencies.yml
Build on new image: https://aidemos.visualstudio.com/MLOps/_build?definitionId=151&_a=summary
AKS is failing due to lack of resources - should be unrelated to this change.
=> update azureml sdk

docs/getting_started.md
We found that some users were skipping the step to install the AML extension, so moving it up to the "Azure Devops setup" section.
=> Move instruction to install AML extension to Azure Devops setup step

.pipelines/diabetes_regression-variables-template.yml, docs/getting_started.md, environment_setup/arm-templates/cloud-environment.json, environment_setup/iac-create-environment-pipeline-arm.yml
=> update arm template to make workspace sku configurable

diabetes_regression/util/model_helper.py
A bug surfaced where first time evaluation of a model fails due to the Model constructor throwing if the model does not exist.
Looking deeper, we see that most calls to get_model expect a possible None response and check at the call site. Unfortunately we get the same WebserviceException class for a model not being found as we do a REST error or similar.
This change is a stopgap mitigation to restore compatibility with the existing callers, and compromises by allowing the model version dependent behavior to continue passing on exceptions.
In a future follow up we should settle on a convention and allow version checks to propagate failure while still giving the possibility for handling a service exception in the caller.
=> Restore call convention compatibility in get_model

.pipelines/diabetes_regression-cd.yml
Recently the template to get the model version had a name associated with the step that sets the variable. We need to also update the variable references in future steps to use the template step name as a prefix. This resulted in the MODEL_VERSION variable causing failures in each CD deployment step since it was not set.
This did not show up in CI because the MODEL_VERSION var is hard coded in the variable group. We should also remove that.
=> Fix CD deployment break

diabetes_regression/ci_dependencies.yml, diabetes_regression/conda_dependencies.yml
https://aidemos.visualstudio.com/MLOps/_build/results?buildId=5068&view=results
=> Update azureml sdk to 1.13

diabetes_regression/ci_dependencies.yml, diabetes_regression/conda_dependencies.yml
#329
https://aidemos.visualstudio.com/MLOps/_build/results?buildId=5123&view=results
=> Update azureml-sdk to use latest

docs/development_setup.md
development_setup.md updated to use install_requirements.sh.
See #158:
> Use conda rather than pip packages when possible (as recommended in AML docs).
> Dev environment is hence also constrained to conda (no more pip install -r requirements.txt).
=> development_setup.md update

.env.example
TRAIN_SCRIPT_PATH value updated from 'training/train.py' to 'training/train_aml.py'.
This is aligned with /.pipelines/diabetes_regression-variables-template.yml.
=> fix TRAIN_SCRIPT_PATH value in .env.example

docs/getting_started.md
Added a clarification, that the AKS compute name comes from the inference cluster, which needs to be created to continue.
=> Added AKS compute name details
